### ISSUE TITLE
networkx is missing when installing

### ISSUE THREAD

**Issue by mheppner** [OmenApps/django-postgresql-dag#5]
When installing from pip, `networkx` doesn't get installed. It's imported in transformations.py at the top, but this may want to be moved to an inline import in `nx_from_queryset()`.

The networkx stuff looks like an in-progress feature, but just wanted to let you know.

**Comment by JackAtOmenApps** [comment]
Yep, it's in-progress work that stalled a couple months ago when things got busy here. Thanks for opening an issue. Should have some time to fix and continue working this.

**Comment by JackAtOmenApps** [comment]
This should be resolved now. If you want to make use of the experimental tools in tranformations.py, you can install django-postgresql-dag with:

`pip install django-postgresql-dag[transforms]`

**Comment by mheppner** [comment]
`networkx` and `pandas` still seem to be required when installing the plain pip package (not with `transforms` specified). 

When importing `from django_postgresql_dag.models import node_factory`, the models.py file imports `from .transformations import _ordered_filter`. The transformations.py file still has the imports of `networkx` and `pandas` declared at the top of the file.

**Comment by JackAtOmenApps** [comment]
@mheppner - Thank you. This should (for real) be corrected now.
